name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET Core Project
      run: dotnet publish BlazorMosque.Client/BlazorMosque.Client.csproj -c Release -o release --nologo

    - name: List contents of release directory
      run: |
        echo "Contents of release directory:"
        ls -R release

    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorMosque\/" \/>/g' release/index.html

    - name: Add .nojekyll file
      run: touch release/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release
